wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.5
    code_path: code/main.py
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.6
device:
  desc: null
  value: cuda:3
epochs_num:
  desc: null
  value: 1
g_lr:
  desc: null
  value: 0.0003
in_channels:
  desc: null
  value: 3
log_each:
  desc: null
  value: 250
num_downs:
  desc: null
  value: 7
out_channels:
  desc: null
  value: 3
train_batch_size:
  desc: null
  value: 1
val_batch_size:
  desc: null
  value: 64
